[package]
name = "regexrust"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "regexrust"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
regex = "^1.10.4"
rustler = "^0.32.1"

[profile.release]
codegen-units = 1
lto = true
